Task 1 unittests
oscamaina/andela-21 pull request #3
Opened 2017-03-09 10:47 UTC by oscamaina

2017-03-09 12:29 UTC, kevintumbo commented on tests/test.py
> +
You forgot to include Y (yes) as the fourth parameter ....so they won't be allocated any livingspace
also staff should not be allocated living space

2017-03-09 12:32 UTC, kevintumbo commented on tests/test.py
> +
Its advised to have a teardown method when you use a setUp method

2017-03-09 12:33 UTC, oscamaina commented on tests/test.py
> +
Aah, thanks for the identification

2017-03-09 12:34 UTC, oscamaina commented on tests/test.py
> +
will you please elaborate

2017-03-09 12:40 UTC, kevintumbo commented on tests/test.py
> +
when you use a setUp method ...it's recommended have a teardown method to release resources
https://docs.python.org/3/library/unittest.html

2017-03-09 12:43 UTC, oscamaina commented on tests/test.py
> +
let me read about it

2017-03-09 17:20 UTC, Gchesta commented on tests/test.py
> +        self.assertIn("Dennis Wachiuri", "room")
what is room in this context? The system does not print into "room" and therefore you can't prove that the system has printed by checking whether the name "Dennis" is in room

2017-03-09 17:20 UTC, Gchesta commented on tests/test.py
> +        self.assertIn("Dennis Person7", unallocated)
same thing as above

2017-03-09 17:34 UTC, Gchesta commented on tests/test.py
> +        self.assertIn("Dennis Person7", unallocated)
Also try to test for the output files that are to be created.

2017-03-09 18:56 UTC, mnjaggah commented on tests/test.py
> +        self.assertIn("Dennis Wachiuri", "room")
since room is a variable, it doesn't require the double quotes

2017-03-09 19:03 UTC, oscamaina commented on tests/test.py
> +        self.assertIn("Dennis Wachiuri", "room")
simple mistake, changing that

2017-03-09 19:04 UTC, oscamaina commented on tests/test.py
> +        self.assertIn("Dennis Wachiuri", "room")
i made a mistake, the room is a variable, it should not be in quotes

2017-03-09 19:05 UTC, mnjaggah commented on tests/test.py
> +class TestPrintAllocatedUnallocated(unittest.TestCase):
Maybe consider creating a new method to test unallocated seperately as you have named the class 'TestPrintAllocatedUnallocated' but only defined one method testing allocations

2017-03-10 08:06 UTC, ianoti requested changes
Consider splitting your tests files into separate files. Make the changes. Good job on the tests.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        room = Office('kigali')
I missed this in the last review, `line 26` should not be there, the Office class should be created inside the `create_room` method.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        self.assertIsInstance(room, Office)
You should be checking assertion (office, Office) change `line 27`.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        room = LivingSpace('java')
same as above, correct this logical error as explained. remove `line 40`

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        self.assertIsInstance(room, LivingSpace)
change assertion to compare `living_space` and `LivingSpace`

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        person = Fellow('Maina','Wekesa')
change lines 77-78 as shown earlier, this is a logical error.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        self.dojo.add_person('Shem','Ogube', 'Staff')
change lines 86-87 it's a logical error, the assertion should test the person created with `add_person`

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +class TestPrintAllocatedUnallocated(unittest.TestCase):
same as Maria's comment above, the class naming and docstrings conflict and aren't clear on the purpose of the test case.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +        self.dojo.add_person('Dennis', 'Person1', 'Fellow', 'Y')
lines 128-131 can be moved to the setUp so that you set up one room being full and one room being empty. the test assertions should test one function at a time. so lines 136 and 137 belong in separate tests.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +
As Kevin stated above, tearDown methods are usually paired with setUp methods, but in this case the only action performed in setUp is instantiating a class. hence a teardown isn't really necessary. The tearDown method is essential when the setUp in the test suite would interfere with the normal operation of other tests. e.g creating a file in setUp would require destroying the file in tearDown.

2017-03-10 08:06 UTC, ianoti commented on tests/test.py
> +import os
What purpose does lines 2-7 serve in your current unit tests? I can't see any implementation.

2017-03-10 08:28 UTC, oscamaina commented on tests/test.py
> +import os
it solves issue of importError. without the lines i get the ModuleNotFoundError.

2017-03-10 08:31 UTC, oscamaina commented on tests/test.py
> +        room = LivingSpace('java')
ok

2017-03-11 20:20 UTC, closed without merging