Task 3 unittests
oscamaina/andela-21 pull request #6
Opened 2017-03-16 04:03 UTC by oscamaina

2017-03-16 05:23 UTC, Gchesta commented on tests/test_database.py
> +        self.assertEqual("App data has been stored in somedb.db database", output)
How does this test that the data has been saved successfully?

2017-03-16 05:28 UTC, Gchesta commented on tests/test_database.py
> +        self.assertEqual(room_count_after - initial_room_count, 5)
Makes sense. Now check the length of the persons too, and their attributes.

2017-03-16 05:28 UTC, Gchesta commented on tests/test_database.py
> +        self.assertEqual("App data has been stored in somedb.db database", output)
Another thing, the format for self.assert is (output, expected output). Just revise that.

2017-03-16 05:30 UTC, oscamaina commented on tests/test_database.py
> +        self.assertEqual("App data has been stored in somedb.db database", output)
Thanks

2017-03-16 06:57 UTC, mnjaggah commented on tests/test_database.py
> +        engine = create_engine('sqlite:///database/somedb.db')
you need to import session maker and create_engine

2017-03-16 06:57 UTC, mnjaggah commented on tests/test_database.py
> +        engine = create_engine('sqlite:///database/somedb.db')
you have used different databases for this test, was that intentional

2017-03-16 08:33 UTC, oscamaina commented on tests/test_database.py
> +        engine = create_engine('sqlite:///database/somedb.db')
It's imported in the dojo file, on this file i am importing everything from dojo

2017-03-16 08:34 UTC, oscamaina commented on tests/test_database.py
> +        engine = create_engine('sqlite:///database/somedb.db')
typo error, fixed

2017-03-16 13:07 UTC, ianoti requested changes
A better way of testing the database functionality would be to have 2 instances of  Dojo(). in one instance of the Dojo() add people and add rooms and perform the save state functionality, in the second instance of Dojo use the load state functionality to recover the people and rooms in the first instance of Dojo. then you assert to check that both instances have equivalent rooms and persons hence testing save state and load state.

2017-03-16 13:07 UTC, ianoti commented on tests/test_database.py
> +        self.dojo.load_state("flask.db")
why are you loading from different database from the one you saved data to?

2017-03-16 13:07 UTC, ianoti commented on tests/test_database.py
> +        engine = create_engine('sqlite:///database/somedb.db')
unittests should test functionality of the app itself, this `create_engine` section from lines 18-25 should not appear in your code. check the data exists by loading from the db and checking the loaded data is equivalent to what you expect.

2017-03-17 06:57 UTC, ianoti requested changes
Your database tests are not logical. you are creating the rooms in the `fdojo` instance but saving the state of the `dojo` instance which has no rooms defined in it. it would be better to save state of `fdojo` and load state in `dojo` 
Another thing, improve the naming of the instances `fdojo` isn't descriptive enough.

2017-03-18 17:17 UTC, jimmykimani approved these changes

2017-03-18 20:24 UTC, closed without merging